#' Keep effects
#'
#' \code{keepef} is used to remove fixed and random effects from repsonse 
#'  variable based on a (linear) mixed-effects model object generated by the
#'  \pkg{lme4} package.
#' 
#' @param model a model object.
#' @param fix a character of coefficient labels.
#' @param ran a named list of integer vectors representing
#'   random effects.
#' @param grouping logical. Should lower-order terms associated with the
#'  ones in \code{fix} also be kept? The details are given under 
#'  'Details'.
#' @param keep.intercept logical. Should the intercept be kept
#'  (default) or be removed?
#' @param inverse logical. If \code{TRUE}, the inverse of the link
#'  function is applied (after the effects are removed).
#' @return \code{keepef} returns a numeric vector. The length of the
#'  vector is equal to the number of observations of the model.   
#'                        
#' @details \code{model} is an object returned by a model fitting 
#'  function of the \pkg{lme4} package, i.e., \code{lmer} for
#'  linear mixed-effects models or \code{glmer} for generalised
#'  linear mixed-effects models.
#'  For more on details on mixed-effects models and partial effects, see
#'  the help page of \code{\link{partial}}.
#'  
#'  TODO: More details on the funcion and its arguments
#'   
#' @seealso \code{\link{remef}} for a wrapper of \code{partial} with 
#'  \code{keep = FALSE}.
#' @export
#' @examples
#' # TODO: some examples

keepef <-
  function(model, fix = NULL, ran = NULL, grouping = FALSE,
           keep.intercept = TRUE, inverse = FALSE)
  {
    partial(model, fix = NULL, ran = NULL, grouping = FALSE,
            keep.intercept = TRUE, inverse = FALSE, keep = TRUE)
  }